# Generated by Django 5.0.7 on 2024-07-29 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('source_latitude', models.FloatField()),
                ('source_longitude', models.FloatField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('distance', models.FloatField()),
                ('date', models.DateField()),
                ('time_taken', models.DurationField()),
                ('is_electric', models.BooleanField()),
                ('mode_of_transport', models.CharField(max_length=50)),
                ('carbon_footprint', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
