# Generated by Django 5.0.7 on 2024-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellog',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
    ]
