# Generated by Django 5.0.7 on 2024-08-18 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellog',
            name='time_duration_fetched',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
