# Generated by Django 5.0.7 on 2024-08-18 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_travellog_time_duration_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellog',
            name='log_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
